// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg9eDYek_tcPJvSjJhDcrxPO9DMp2QeU4',
    appId: '1:83704657261:android:d6c7a3ccac0c19ca319664',
    messagingSenderId: '83704657261',
    projectId: 'spacespace-d0912',
    storageBucket: 'spacespace-d0912.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq0aBOxlAWlNvLjwzCH9tcf3Rf7NtpdGU',
    appId: '1:918605907062:ios:9d3a818e244e997f080b57',
    messagingSenderId: '918605907062',
    projectId: 'spacespace-d0912',
    storageBucket: 'spacespace-d0912.appspot.com',
    iosBundleId: 'com.joy.spaceTexting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyA9t9OFlroVHy1YWWkbV0WwSxNO8Z1-sT0",
    authDomain: "spacespace-d0912.firebaseapp.com",
    projectId: "spacespace-d0912",
    storageBucket: "spacespace-d0912.firebasestorage.app",
    messagingSenderId: "83704657261",
    appId: "1:83704657261:web:c6e9f8531e411d30319664",
    measurementId: "G-WZFFCMVN34"
  );
}
